@extends('layouts.app')

@section('content')
<div class="container bg-body p-4 rounded">
    <h1 class="mb-4">Two-Factor Authentication</h1>

    @if (auth()->user()->two_factor_secret)
        @if (!auth()->user()->two_factor_confirmed_at)
            <div id="2fa-form-modal" class="modal fade" tabindex="-1">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Enable 2FA</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="mb-4">
                                Scan the following QR code with the authenticator app of your choosing, then enter the code generated by the app.
                            </div>
                            <div class="mb-3 text-center">
                                {!! auth()->user()->twoFactorQrCodeSvg() !!}
                            </div>
                            <form action="{{ url('/user/confirmed-two-factor-authentication') }}" method="post">
                                @csrf
                                <div class="mb-3">
                                    <label for="code" class="form-label">Code</label>
                                    <input type="text" class="form-control" id="code" name="code">
                                </div>
                                <button type="submit" class="btn btn-primary">Confirm</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endif


    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-body">
                Successfully enabled Two-Factor Authentication!
            </div>
        </div>
    </div>

    <div>
        <a class="btn btn-danger" href="{{ url('user/two-factor-authentication') }}"
            onclick="event.preventDefault();
                        document.getElementById('disable-2fa-form').submit();">
            Disable 2FA
        </a>
        <form id="disable-2fa-form" action="{{ url('user/two-factor-authentication') }}" method="POST" class="d-none">
            @csrf
            @method('DELETE')
        </form>
    </div>

    @else
    <p class="mb-2">Enable Two-Factor Authentication for maximum security</p>
    <a class="btn btn-primary" href="{{ url('user/two-factor-authentication') }}"
        onclick="event.preventDefault();
                document.getElementById('enable-2fa-form').submit();">
        Enable 2FA
    </a>

    <form id="enable-2fa-form" action="{{ url('user/two-factor-authentication') }}" method="POST" class="d-none">
        @csrf
    </form>
    @endif
</div>
@endsection


@if (session('status') == 'two-factor-authentication-confirmed')
@section('scripts')
<script>
    var toast = new bootstrap.Toast(document.getElementById('liveToast'));
    toast.show();
</script>
@endsection

@endif
@if (auth()->user()->two_factor_secret && !auth()->user()->two_factor_confirmed_at)
@section('scripts')
<script>
    $(document).ready(function() {
        $('#2fa-form-modal').modal('show');
    });
</script>
@endsection
@endif
